title: "Buttons!"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: "12em"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for banners, where it will be placed in front of busy images.
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
  basic-cart:
    title: "Basic-cart"
    description: |
      This button is specifically for the add-to-cart button feature.
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Add to cart"
  borderless:
    title: "Borderless"
    description: |
      This button is a basic button with no borders.
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
  dark:
    title: "Dark"
    description: |
      This button is dark and used with lighter backgrounds.
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
  ghost-cart:
    title: "Ghost-cart"
    description: |
      This button is specifically for the add-to-cart button feature when placed over an image.
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Add to cart"
  light:
    title: "Light"
    description: |
      This button is light and used with darker backgrounds.
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
  shell:
    title: "Shell"
    description: |
      This is the shell icon button and used in special places.
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
  special:
    title: "Special"
    description: |
      The special button is used in special places, usually for contrast or special actions.
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
