title: "Buttons!"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: "12em"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for banners, where it will be placed in front of busy images.
    width: "12em"
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
  borderless:
    title: "Borderless"
    description: |
      This button is a basic button with no borders.
    width: "12em"
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
  dark:
    title: "Dark"
    description: |
      This button is dark and used with lighter backgrounds.
    width: "12em"
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
  light:
    title: "Light"
    description: |
      This button is light and used with darker backgrounds.
    width: "12em"
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
      - name: url
        type: url
        example: "/products/"
  special:
    title: "Special"
    description: |
      The special button is used in special places, usually for contrast or special actions.
    width: "12em"
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Get this Clam"
  icon:
    title: "Icon"
    description: |
      Basic icon button.
    width: "12em"
    background: "--color-primary-light"
    fields:
      - name: title
        type: string
        example: "Add To Cart"
      - name: image
        type: image
        example: "icons.svg#cart-icon"
