title: "Buttons!"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  image:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: 400
    fields:
      - name: title
        type: string
        example: "Conch"
      - name: details
        type: string
        example: "The coveted conch!"
      - name: image
        type: image
        example: "conch.jpg"
      - name: button_text
        type: string
        example: "Get this Conch"
  featured:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: 500
    fields:
      - name: title
        type: string
        example: "Conch"
      - name: details
        type: string
        example: "The coveted conch!"
      - name: image
        type: image
        example: "conch.jpg"
      - name: button_text
        type: string
        example: "Get this Conch"
  icon:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: 400
    fields:
      - name: title
        type: string
        example: "Limpet"
      - name: details
        type: string
        example: "Mayhaps you'll find a pearl?"
      - name: button_text
        type: string
        example: "Browse Shells"
  products:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: 400
    fields:
      - name: title
        type: string
        example: "Conch"
      - name: details
        type: string
        example: "The coveted conch!"
      - name: image
        type: image
        example: "conch.jpg"
      - name: button_text
        type: string
        example: "Get this Conch"
  related:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: 400
    fields:
      - name: title
        type: string
        example: "Conch"
      - name: details
        type: string
        example: "The coveted conch!"
      - name: image
        type: image
        example: "conch.jpg"
      - name: button_text
        type: string
        example: "Get this Conch"
