title: "Cards"
description: |
  Cards are used to display products and images.

patterns:
  basic:
    title: "Basic"
    description: |
      The basic card is used in most situations.
    padding: 2em
    fields:
      - name: image
        type: image
        example: "conch.jpg"
      - name: title
        type: string
        example: "Conch Shell"
      - name: details
        type: string
        example: "The coveted conch... omg."
      - name: price
        type: value
        example: "$12.99"
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: product

  featured:
    title: "Featured"
    description: |
      The featured card is used for popular products or products that are on sale.
    padding: 2em
    fields:
      - name: image
        type: image
        example: "conch.jpg"
      - name: title
        type: string
        example: "Conch Shell"
      - name: details
        type: string
        example: "The coveted conch... omg."
      - name: price
        type: value
        example: "$12.99"

  products:
    title: "Products"
    description: |
      The product card is used to display most products using a grid system.
    padding: 2em
    fields:
      - name: image
        type: image
        example: "conch.jpg"
      - name: title
        type: string
        example: "Conch Shell"
      - name: details
        type: string
        example: "The coveted conch... omg."
      - name: price
        type: value
        example: "$12.99"
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: product

  related:
    title: "Related"
    description: |
      The related card is used for displaying related products.
    padding: 2em
    fields:
      - name: image
        type: image
        example: "conch.jpg"
      - name: title
        type: string
        example: "Conch Shell"
      - name: details
        type: string
        example: "The coveted conch... omg."
      - name: price
        type: value
        example: "$12.99"
