title: "Banners"
description: |
  Banners should be used on the home page, landing pages, and call-to-actions.

patterns:
  call-to-action:
    title: "Call-to-action"
    description: |
      The call-to-action banner is used for call-to-actions.
    fields:
      - name: title
        type: string
        example: "SHELLS SHELLS SHELLS!"
      - name: details
        type: string
        example: "Shellllllllllllllllssssssssss"
      - name: image
        type: image
        example: "banner-6.jpg"
      - name: button_text
        type: string
        example: "See collection"
      - name: button_url
        type: url
        example: "/products/"
        required: false
  featured:
    title: "Featured"
    description: |
      The featured banner is used to showcase new and popular items.
    fields:
      - name: title
        type: string
        example: "New and Popular Shells! Yeah!"
      - name: details
        type: string
        example: "Shellllllllllllllllssssssssss"
      - name: image
        type: image
        example: "banner-1.jpg"
  hero:
    title: "Hero"
    description: |
      The hero banner is used on the home page.
    fields:
      - name: title
        type: string
        example: "Welcome to shell HELL!"
      - name: details
        type: string
        example: "Just kidding"
      - name: image
        type: image
        example: "banner-6.jpg"
