patterns:
  top:
    fields:
      - name: title
        type: string
        example: "Conch"
      - name: details
        type: string
        example: "The coveted conch!"
      - name: image
        type: image
        example: "conch.jpg"
      - name: button_text
        type: string
        example: "Get this Conch"
  icon:
    fields:
      - name: title
        type: string
        example: "Conch"
      - name: details
        type: string
        example: "The coveted conch!"
      - name: image
        type: image
        example: "conch.jpg"
      - name: button_text
        type: string
        example: "Get this Conch"
