title: "Banners"
description: |
  Banners should be used on the home page, landing pages, and call-to-actions.

patterns:
  hero:
    title: "Hero"
    description: |
      The hero banner is used on the home page.
  icon:
    title: "Icon"
    description: |
      The icon banner is used for some call-to-actions.
  featured:
    title: "Featured"
    description: |
      The featured banner is used to showcase new and popular items.
  call-to-action:
    title: "Call-to-action"
    description: |
      The call-to-action banner is used for call-to-actions.
